# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vip_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=30)),
                ('good_price', models.FloatField(max_length=8)),
                ('good_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('good_reserve1', models.CharField(blank=True, max_length=30, null=True)),
                ('good_reserve2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vip_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_person_id', models.IntegerField(default=0)),
                ('order_name', models.CharField(max_length=50)),
                ('order_good', models.ManyToManyField(to='vms.vip_good')),
            ],
        ),
        migrations.CreateModel(
            name='vip_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_name', models.CharField(max_length=20)),
                ('vip_sex', models.IntegerField()),
                ('vip_phone', models.CharField(max_length=20)),
                ('vip_level', models.IntegerField()),
                ('vip_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('vip_reserve1', models.CharField(blank=True, max_length=30, null=True)),
                ('vip_reserve2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vip_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_person_id', models.IntegerField(default=0)),
                ('point_value', models.FloatField(max_length=8)),
                ('point_last_value', models.FloatField(max_length=8)),
                ('point_last_time', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('point_reserve1', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vip_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=30)),
                ('server_price', models.FloatField(max_length=8)),
                ('server_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('server_reserve1', models.CharField(blank=True, max_length=30, null=True)),
                ('server_reserve2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vip_order',
            name='order_server',
            field=models.ManyToManyField(to='vms.vip_server'),
        ),
    ]
